### ISSUE TITLE
Middle Layer Implementation

### ISSUE THREAD

**Issue by NazirNayal8** [yhassanzadeh13/SEALA_Client#19]
* To implement a middle layer that mediates between `Overlay` and `Underlay`.
* The Middle Layer has instances of both overlay and underlay
* The Overlay has an instance of Middle layer, and Underlay has instance of Middle Layer
* Both Overlay and Underlay use middle layer  to communicate in both ways directions.
* Middle Layer guarantees thread safety for requests from underlay to overlay and vice versa.
* One way to handle requests on both directions would be to have two thread safe queues in middle layer to which requests are appended and processed in both directions, but this handling detail can be left to your discretion.
* To add unit tests.

**Comment by utkn** [comment]
Dear @NazirNayal8,

I am currently implementing the middle layer. However, there is something unclear to me. Could you explain what exactly do you mean by thread-safety? Do you mean that no two requests should be handled at the same time? Can't we simply use thread safe resources (i.e. `ConcurrentLookupTable`) to ensure thread safety?

Thanks,

Utkan

**Comment by NazirNayal8** [comment]
Dear @utkn ,

Thank you for bringing up this point. My idea about how the middle layer works is ,as described, to maintain queues to which requests are appended in from both sides and routed to the other side, so reading and writing from these queues would be protected, but actually after thinking since the middle layer does not have a state it is pointless to have thread safety in the middle layer, the state of the overlay should be protected by the overlay (mostly from update requests). Hence I believe it would suffice to have the middle layer simply route the requests. Please let me know if my idea is clear or if I have missed something. Thank you
