### ISSUE TITLE
Setup Logger and Maven 

### ISSUE THREAD

**Issue by NazirNayal8** [yhassanzadeh13/SEALA_Client#8]
* To setup a logger using log4j.
* To structure the project in Maven

**Comment by thep2p** [comment]
Dear @Shamdan17 and @NazirNayal8,

Regarding the logging, please note that we need 3 [levels of logging](https://logging.apache.org/log4j/2.x/manual/customloglevels.html) enabled for Skip Graph node:
- Info: for high-level Skip Graph operations, e.g., joining and leaving the system, putting or getting a data object, etc. 
- Debug: for low-level (critical) functions, e.g., when a node receives a search message to route, or when it updates an entry in its lookup table. 
- Error: for protocol-level errors, e.g., when a node is double visited on the same search path (please make an issue for this specific error if it has not been covered, this can be the root of several potential bugs later). 

Thank you
